[package]
name = "meganz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.45"
regex = "1.13.1"
mega = {path="mega"}
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }
shared_types = { workspace = true }
client = { workspace = true }
tokio = { version = "1.52.3", features = ["rt", "time"] }
