[package]
name = "meganz"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"] 

[dependencies]
shared_types = { workspace = true }
client = { workspace = true }
serde.workspace = true
serde_json = "1.0.151"
url = "2.5.8"
reqwest = { version = "0.12.22", features = ["socks"] }
mega = {git="https://github.com/git4unrealnondev/mega-rs"} 
text_trees = "0.1.2"
tokio = "1.53.1"
block-modes = "0.9.1"
