[package]
name = "shared_types"
version = "0.1.0"
edition = "2024"

[dependencies]
redact = { git = "https://github.com/git4unrealnondev/redact", features = ["serde", "bitcode"] }
serde = { workspace = true }
bitcode = { workspace = true }
strum_macros = {optional=true, workspace=true}
strum = {optional=true, workspace=true}

[features]
default = []

strum = ["dep:strum_macros", "dep:strum"]
